nmMode: hardlinks-local

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: 3ca2fd4b-79dc-43dc-9f8d-6070356d26b3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
