export type Events =
  | 'TEST_RUN_STARTED'
  | 'TEST_COMPLETED'
  | 'ALL_RUNNING_TESTS_FINISHED'
  | 'REMOVE_FIELD'
  | 'RESET_FIELD'
  | 'RESET_SUITE'
  | 'SUITE_RUN_STARTED'
  | 'SUITE_CALLBACK_RUN_FINISHED'
  | 'DONE_TEST_OMISSION_PASS';
