import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    globals: true,
    include: ['./**/__tests__/*.test.ts'],
    setupFiles: [resolve(__dirname, '../../', 'vx/config/vitest/customMatchers.ts')],
  },
  root: __dirname,
  resolve: {
    alias: {
      ruleResult: resolve(__dirname, 'src/ruleResult.ts'),
      n4sTypes: resolve(__dirname, 'src/n4sTypes.ts'),
      n4s: resolve(__dirname, 'src/n4s.ts'),
      lazy: resolve(__dirname, 'src/lazy.ts'),
      extendLogic: resolve(__dirname, 'src/extendLogic.ts'),
      enforceContext: resolve(__dirname, 'src/enforceContext.ts'),
      eager: resolve(__dirname, 'src/eager.ts'),
      compose: resolve(__dirname, 'src/compose.ts'),
      toNumber: resolve(__dirname, 'src/utils/toNumber.ts'),
      regex: resolve(__dirname, 'src/utils/regex.ts'),
      RuleRunReturn: resolve(__dirname, 'src/utils/RuleRunReturn.ts'),
      RuleInstance: resolve(__dirname, 'src/utils/RuleInstance.ts'),
      stringRules: resolve(__dirname, 'src/rules/stringRules.ts'),
      objectRules: resolve(__dirname, 'src/rules/objectRules.ts'),
      numberRules: resolve(__dirname, 'src/rules/numberRules.ts'),
      nullishRules: resolve(__dirname, 'src/rules/nullishRules.ts'),
      generalRules: resolve(__dirname, 'src/rules/generalRules.ts'),
      genRuleChain: resolve(__dirname, 'src/rules/genRuleChain.ts'),
      commonLength: resolve(__dirname, 'src/rules/commonLength.ts'),
      commonContainer: resolve(__dirname, 'src/rules/commonContainer.ts'),
      commonComparison: resolve(__dirname, 'src/rules/commonComparison.ts'),
      booleanRules: resolve(__dirname, 'src/rules/booleanRules.ts'),
      arrayRules: resolve(__dirname, 'src/rules/arrayRules.ts'),
      RuleInstanceBuilder: resolve(__dirname, 'src/rules/RuleInstanceBuilder.ts'),
      startsWith: resolve(__dirname, 'src/rules/string/startsWith.ts'),
      notMatches: resolve(__dirname, 'src/rules/string/notMatches.ts'),
      matches: resolve(__dirname, 'src/rules/string/matches.ts'),
      isString: resolve(__dirname, 'src/rules/string/isString.ts'),
      isNotBlank: resolve(__dirname, 'src/rules/string/isNotBlank.ts'),
      isBlankString: resolve(__dirname, 'src/rules/string/isBlankString.ts'),
      endsWith: resolve(__dirname, 'src/rules/string/endsWith.ts'),
      doesNotStartWith: resolve(__dirname, 'src/rules/string/doesNotStartWith.ts'),
      doesNotEndWith: resolve(__dirname, 'src/rules/string/doesNotEndWith.ts'),
      shape: resolve(__dirname, 'src/rules/schemaRules/shape.ts'),
      schemaRulesTypes: resolve(__dirname, 'src/rules/schemaRules/schemaRulesTypes.ts'),
      schemaRulesLazyTypes: resolve(__dirname, 'src/rules/schemaRules/schemaRulesLazyTypes.ts'),
      schemaRules: resolve(__dirname, 'src/rules/schemaRules/schemaRules.ts'),
      partial: resolve(__dirname, 'src/rules/schemaRules/partial.ts'),
      optional: resolve(__dirname, 'src/rules/schemaRules/optional.ts'),
      loose: resolve(__dirname, 'src/rules/schemaRules/loose.ts'),
      isArrayOf: resolve(__dirname, 'src/rules/schemaRules/isArrayOf.ts'),
      isValueOf: resolve(__dirname, 'src/rules/object/isValueOf.ts'),
      isKeyOf: resolve(__dirname, 'src/rules/object/isKeyOf.ts'),
      isNumeric: resolve(__dirname, 'src/rules/numeric/isNumeric.ts'),
      numberNotEquals: resolve(__dirname, 'src/rules/number/numberNotEquals.ts'),
      lessThanOrEquals: resolve(__dirname, 'src/rules/number/lessThanOrEquals.ts'),
      lessThan: resolve(__dirname, 'src/rules/number/lessThan.ts'),
      isPositive: resolve(__dirname, 'src/rules/number/isPositive.ts'),
      isOdd: resolve(__dirname, 'src/rules/number/isOdd.ts'),
      isNumber: resolve(__dirname, 'src/rules/number/isNumber.ts'),
      isNotBetween: resolve(__dirname, 'src/rules/number/isNotBetween.ts'),
      isNegative: resolve(__dirname, 'src/rules/number/isNegative.ts'),
      isEven: resolve(__dirname, 'src/rules/number/isEven.ts'),
      isBetween: resolve(__dirname, 'src/rules/number/isBetween.ts'),
      greaterThanOrEquals: resolve(__dirname, 'src/rules/number/greaterThanOrEquals.ts'),
      isUndefined: resolve(__dirname, 'src/rules/nullish/isUndefined.ts'),
      isNullish: resolve(__dirname, 'src/rules/nullish/isNullish.ts'),
      isNull: resolve(__dirname, 'src/rules/nullish/isNull.ts'),
      notEquals: resolve(__dirname, 'src/rules/general/notEquals.ts'),
      isTruthy: resolve(__dirname, 'src/rules/general/isTruthy.ts'),
      isNotUndefined: resolve(__dirname, 'src/rules/general/isNotUndefined.ts'),
      isNotString: resolve(__dirname, 'src/rules/general/isNotString.ts'),
      isNotNumeric: resolve(__dirname, 'src/rules/general/isNotNumeric.ts'),
      isNotNumber: resolve(__dirname, 'src/rules/general/isNotNumber.ts'),
      isNotNullish: resolve(__dirname, 'src/rules/general/isNotNullish.ts'),
      isNotNull: resolve(__dirname, 'src/rules/general/isNotNull.ts'),
      isNotNaN: resolve(__dirname, 'src/rules/general/isNotNaN.ts'),
      isNotEmpty: resolve(__dirname, 'src/rules/general/isNotEmpty.ts'),
      isNotBoolean: resolve(__dirname, 'src/rules/general/isNotBoolean.ts'),
      isNotArray: resolve(__dirname, 'src/rules/general/isNotArray.ts'),
      isNaN: resolve(__dirname, 'src/rules/general/isNaN.ts'),
      isFalsy: resolve(__dirname, 'src/rules/general/isFalsy.ts'),
      isEmpty: resolve(__dirname, 'src/rules/general/isEmpty.ts'),
      isBlank: resolve(__dirname, 'src/rules/general/isBlank.ts'),
      equals: resolve(__dirname, 'src/rules/general/equals.ts'),
      condition: resolve(__dirname, 'src/rules/general/condition.ts'),
      oneOf: resolve(__dirname, 'src/rules/compoundRules/oneOf.ts'),
      noneOf: resolve(__dirname, 'src/rules/compoundRules/noneOf.ts'),
      compoundRulesTypes: resolve(__dirname, 'src/rules/compoundRules/compoundRulesTypes.ts'),
      compoundRules: resolve(__dirname, 'src/rules/compoundRules/compoundRules.ts'),
      anyOf: resolve(__dirname, 'src/rules/compoundRules/anyOf.ts'),
      allOf: resolve(__dirname, 'src/rules/compoundRules/allOf.ts'),
      proxyHandlers: resolve(__dirname, 'src/rules/chainBuilder/proxyHandlers.ts'),
      lazyRegistry: resolve(__dirname, 'src/rules/chainBuilder/lazyRegistry.ts'),
      chainExecutor: resolve(__dirname, 'src/rules/chainBuilder/chainExecutor.ts'),
      chainBuilder: resolve(__dirname, 'src/rules/chainBuilder/chainBuilder.ts'),
      isTrue: resolve(__dirname, 'src/rules/boolean/isTrue.ts'),
      isFalse: resolve(__dirname, 'src/rules/boolean/isFalse.ts'),
      isBoolean: resolve(__dirname, 'src/rules/boolean/isBoolean.ts'),
      isArrayRule: resolve(__dirname, 'src/rules/array/isArrayRule.ts'),
      includes: resolve(__dirname, 'src/rules/array/includes.ts'),
      typeRules: resolve(__dirname, 'src/lazy/typeRules.ts'),
      ruleAdapter: resolve(__dirname, 'src/lazy/ruleAdapter.ts'),
      isURL: resolve(__dirname, 'src/exports/isURL.ts'),
      email: resolve(__dirname, 'src/exports/email.ts'),
      date: resolve(__dirname, 'src/exports/date.ts'),
      typeUtils: resolve(__dirname, 'src/eager/typeUtils.ts'),
      ruleRegistry: resolve(__dirname, 'src/eager/ruleRegistry.ts'),
      ruleCallGenerator: resolve(__dirname, 'src/eager/ruleCallGenerator.ts'),
      eagerTypes: resolve(__dirname, 'src/eager/eagerTypes.ts'),
      allRules: resolve(__dirname, 'src/eager/allRules.ts')
    }
  },
});