import exec from 'vx/exec.js';
import * as logger from 'vx/logger.js';
import joinTruthy from 'vx/util/joinTruthy.js';
import * as taggedBranch from 'vx/util/taggedBranch.js';
import { usePackage } from 'vx/vxContext.js';
import vxPath from 'vx/vxPath.js';

// Data generated by the release pipeline and provided to the publish step.
// - tag: Optional npm dist-tag computed from branch/tag rules (e.g. next/dev/nightly).
// - tagId: The git tag identifier used by the release flow.
// - versionToPublish: The resolved version string (semantic version or pre-release tag id).
type PublishData = { tag?: string; tagId: string; versionToPublish: string };

function publishPackage({ tag, tagId, versionToPublish }: PublishData): void {
  // Package context is set by the release orchestrator before this step executes.
  const packageName = usePackage();

  // This step is invalid without package context because we cannot construct paths
  // or derive package-specific publish commands.
  if (!packageName) {
    throw new Error('Package context is required for publishing.');
  }

  // Respect branch policy. If publishing is not allowed, exit this step early.
  if (!shouldRelease(versionToPublish)) {
    logger.info(`❌  Not in release branch. Skipping publish.`);
    return;
  }

  // Resolve the effective npm tag used for `npm publish`.
  // This is intentionally explicit to avoid npm trying to apply `latest`
  // in scenarios where that would fail.
  const publishTag = pickPublishTag(tag);

  // High-signal logging so CI output clearly shows what we intend to publish.
  logger.info(`🚀 Publishing package ${packageName}.
    Version: ${versionToPublish}
    Tag Id: ${tagId}
    Publish Tag: ${publishTag}`);

  // Build the command in tokenized form so optional parts can be omitted safely.
  const command = genPublishCommand(packageName, publishTag);

  // In current flow, ephemeral local tags are created only when a dist-tag exists.
  // Keep that assumption explicit via an intent flag.
  const isEphemeralTag = Boolean(tag);

  try {
    // Configure git and execute publish.
    execCommandWithGitConfig(command);
  } finally {
    // Ensure cleanup runs on both success and failure.
    clearTag({ isEphemeralTag, tagId });
  }
}

export default publishPackage;

function pickPublishTag(tag?: string): string | undefined {
  // If release logic already provided a tag, always honor it.
  if (tag) {
    return tag;
  }

  // On release-keep-version we may publish a version lower than npm `latest`.
  // Returning `next` prevents npm from implicitly attempting to write `latest`.
  if (taggedBranch.isReleaseKeepVersionBranch) {
    return 'next';
  }

  // Undefined means "no explicit --tag", allowing default npm behavior.
  return undefined;
}

function clearTag({
  isEphemeralTag,
  tagId,
}: {
  isEphemeralTag: boolean;
  tagId?: string;
}): void {
  // We only clean up tags that were created as ephemeral release artifacts.
  if (isEphemeralTag && tagId) {
    // Local cleanup only. It should never fail the release step.
    exec(`git tag -d ${tagId} || echo "git tag not found. skipping."`, {
      exitOnFailure: false,
      throwOnFailure: false,
    });
  }
}

function execCommandWithGitConfig(command: Array<string | undefined>): void {
  const { EMAIL_ADDRESS, GIT_NAME } = process.env;

  logger.info('Configuring git identity for release publish.');

  // `--replace-all` prevents failures when CI/global git config already has
  // multiple values for user identity keys.
  exec(`git config --global --replace-all user.email "${EMAIL_ADDRESS}"`, {
    silent: true,
    throwOnFailure: true,
  });
  exec(`git config --global --replace-all user.name "${GIT_NAME}"`, {
    silent: true,
    throwOnFailure: true,
  });

  // Publish runs with throwOnFailure so callers can run cleanup in finally.
  exec(joinTruthy(command, ' '), { throwOnFailure: true });
}

function genPublishCommand(
  packageName: string,
  tag?: string,
): Array<string | undefined> {
  // Use npm directly (not yarn npm publish) so OIDC trusted publishing works
  // correctly in GitHub Actions.
  return [
    `cd ${vxPath.package(packageName)} && npm publish`,
    // Include dist-tag only when explicitly set.
    tag && `--tag ${tag}`,
    // npm provenance is recommended for trusted publishing.
    `--provenance`,
  ];
}

function shouldRelease(_versionToUse: string): boolean {
  // Release-keep-version is a valid publish path and must not be blocked.
  return (
    taggedBranch.branchAllowsRelease || taggedBranch.isReleaseKeepVersionBranch
  );
}
