import exec from 'vx/exec.js';
import * as logger from 'vx/logger.js';
import joinTruthy from 'vx/util/joinTruthy.js';
import * as taggedBranch from 'vx/util/taggedBranch.js';
import { usePackage } from 'vx/vxContext.js';
import vxPath from 'vx/vxPath.js';

// Data generated by the release pipeline and provided to the publish step.
// - tag: Optional npm dist-tag computed from branch/tag rules (e.g. next/dev/nightly).
// - tagId: The git tag identifier used by the release flow.
// - versionToPublish: The resolved version string (semantic version or pre-release tag id).
type PublishData = { tag?: string; tagId: string; versionToPublish: string };

function publishPackage({ tag, tagId, versionToPublish }: PublishData): void {
  // Package context is set by the release orchestrator before this step executes.
  const packageName = usePackage();

  // This step is invalid without package context because we cannot construct paths
  // or derive package-specific publish commands.
  if (!packageName) {
    throw new Error('Package context is required for publishing.');
  }

  // High-signal logging so CI output clearly shows what we intend to publish.
  logger.info(`🚀 Publishing package ${usePackage()}.
    Version: ${versionToPublish}
    Tag Id: ${tagId}
    Tag: ${tag}`);

  // Respect branch policy. If publishing is not allowed, exit this step early.
  if (!shouldRelease(versionToPublish)) {
    return logger.info(`❌  Not in release branch. Skipping publish.`);
  }

  // Resolve the effective npm tag used for `npm publish`.
  // This is intentionally explicit to avoid npm trying to apply `latest`
  // in scenarios where that would fail.
  const publishTag = pickPublishTag(tag);

  // Build the command in tokenized form so optional parts can be omitted safely.
  const command = genPublishCommand(publishTag);

  // Configure git and execute publish in one shell script. Git identity is needed
  // for release side effects and consistency in CI environments.
  execCommandWithGitConfig(command);

  // Clean up ephemeral local tags created during release flow.
  clearTag(tag, tagId);
}

export default publishPackage;

function pickPublishTag(tag?: string): string | undefined {
  // If release logic already provided a tag, always honor it.
  if (tag) {
    return tag;
  }

  // On release-keep-version we may publish a version lower than npm `latest`.
  // Returning `next` prevents npm from implicitly attempting to write `latest`.
  if (taggedBranch.isReleaseKeepVersionBranch) {
    return 'next';
  }

  // Undefined means "no explicit --tag", allowing default npm behavior.
  return undefined;
}

function clearTag(tag?: string, tagId?: string): void {
  // We only clean up if both pieces exist and represent an actual tag flow.
  if (tag && tagId) {
    // Local cleanup only. It should never fail the release step.
    exec(`git tag -d ${tagId} || echo "git tag not found. skipping."`, {
      exitOnFailure: false,
      throwOnFailure: false,
    });
  }
}

function execCommandWithGitConfig(command: Array<string | undefined>): void {
  const { EMAIL_ADDRESS, GIT_NAME } = process.env;

  logger.info(
    `Setting git config:
    Email "${EMAIL_ADDRESS}"
    Name "${GIT_NAME}"`,
  );

  exec(
    // `--replace-all` prevents failures when CI/global git config already has
    // multiple user.email values.
    `git config --global --replace-all user.email "${EMAIL_ADDRESS}"
git config --global user.name "${GIT_NAME}"
${joinTruthy(command, ' ')}`,
    { exitOnFailure: false },
  );
}

function genPublishCommand(tag?: string): Array<string | undefined> {
  const packageName = usePackage();

  // Defensive check: command generation requires package context.
  if (!packageName) {
    throw new Error('Package context is required for publishing.');
  }

  // Use npm directly (not yarn npm publish) so OIDC trusted publishing works
  // correctly in GitHub Actions.
  return [
    `cd ${vxPath.package(packageName)} && npm publish`,
    // Include dist-tag only when explicitly set.
    tag && `--tag ${tag}`,
    // npm provenance is recommended for trusted publishing.
    `--provenance`,
  ];
}

function shouldRelease(_versionToUse: string): boolean {
  // Branch gate is centralized in taggedBranch utilities.
  return taggedBranch.branchAllowsRelease;
}
