import fs from 'fs';

import packageExports from '../packageExports.js';
import { packageNames } from '../packageNames.js';

import * as logger from 'vx/logger.js';
import vxPath from 'vx/vxPath.js';

/**
 * Generates .npmignore files for all packages based on exports.
 * @returns {void}
 */

export default function genNpmIgnore() {
  logger.info('Generating .npmignore files...');

  packageNames.list.forEach(packageName => {
    const npmIgnorePath = vxPath.packageNpmIgnore(packageName);

    let existingContent = template;

    if (fs.existsSync(npmIgnorePath)) {
      existingContent = fs.readFileSync(npmIgnorePath, 'utf8');
    }

    const deconstructed = existingContent.split(/(#.*)/g).filter(Boolean); // [comment, content, comment, content]

    deconstructed[1] = genAutoSection(packageExports[packageName]);

    const newContent = deconstructed.join('');

    if (existingContent === newContent) {
      logger.log(`✅ ${packageName} .npmignore is up to date. Skipping.`);
      return;
    }

    logger.log(`📝 Writing .npmignore file for ${packageName}`);

    fs.writeFileSync(npmIgnorePath, newContent, 'utf8');
  });

  logger.info('👌 Done generating .npmignore files.\n');
}

const template = `# Autogenerated section. Do not edit manually.



# Manual Section. Edit at will.`;

/**
 * Generates the auto-managed section of .npmignore.
 * @param {string[]} packageExports List of export entry points.
 * @returns {string} Generated file section.
 */
function genAutoSection(packageExports) {
  return `
node_modules
src
!types/
!dist/
tsconfig.json
${packageExports.map(packageExport => `!${packageExport}/`).join('\n')}

`;
}
