console.log('GITHUB_REF', process.env.GITHUB_REF); // eslint-disable-line
console.log('GITHUB_REPOSITORY', process.env.GITHUB_REPOSITORY); // eslint-disable-line
console.log('GITHUB_EVENT_NAME', process.env.GITHUB_EVENT_NAME); // eslint-disable-line
console.log('GITHUB_SHA', process.env.GITHUB_SHA); // eslint-disable-line
console.log('NPM_TOKEN', process.env.NPM_TOKEN); // eslint-disable-line
console.log('RELEASE_BRANCH', process.env.RELEASE_BRANCH); // eslint-disable-line
console.log('STABLE_BRANCH', process.env.STABLE_BRANCH); // eslint-disable-line
console.log('LATEST_BRANCH', process.env.LATEST_BRANCH); // eslint-disable-line
console.log('CURRENT_BRANCH', process.env.CURRENT_BRANCH); // eslint-disable-line
