/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'get_started',
    {
      type: 'category',
      label: 'Usage with Frameworks',
      collapsed: false,
      items: [
        'usage_with_frameworks/react',
        'usage_with_frameworks/vue',
        'usage_with_frameworks/svelte',
        'usage_with_frameworks/vanilla',
      ],
    },
    'concepts',
    {
      type: 'category',
      label: 'Writing Your Suite',
      items: [{ type: 'autogenerated', dirName: 'writing_your_suite' }],
    },
    {
      type: 'category',
      label: 'Writing Tests',
      items: [{ type: 'autogenerated', dirName: 'writing_tests' }],
    },
    {
      type: 'category',
      label: 'Enforce (Assertions)',
      items: [{ type: 'autogenerated', dirName: 'enforce' }],
    },
    {
      type: 'category',
      label: 'Utilities',
      items: [{ type: 'autogenerated', dirName: 'utilities' }],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [{ type: 'autogenerated', dirName: 'recipes' }],
    },
    'understanding_state',
    'suite_serialization',
    'server_side_validations',
    'typescript_support',
    'api_reference',
    {
      type: 'category',
      label: 'Community Resources',
      items: [{ type: 'autogenerated', dirName: 'community_resources' }],
    },
    'vest_vs_the_rest',
    'upgrade_guide',
  ],
};

module.exports = sidebars;
