/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'get_started',
    'tutorials',
    {
      type: 'category',
      label: 'Usage with Frameworks',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'usage_with_frameworks' }],
    },
    'concepts',
    {
      type: 'category',
      label: 'Solve a Validation Problem',
      collapsed: false,
      items: [
        'guides/async-validation-race-conditions',
        'guides/focused-validation',
        'guides/dependent-fields',
        'guides/multi-step-workflows',
        'guides/conditional-sections',
        'guides/dynamic-lists',
        'guides/validation-status',
        'guides/memo-and-debounce',
        'guides/client-server-validation',
        'guides/typed-schemas',
        'guides/form-and-schema-integration',
        'guides/production-architecture',
        'guides/nextjs-server-actions',
        'guides/when-not-to-use-vest',
      ],
    },
    {
      type: 'category',
      label: 'Writing Your Suite',
      items: [{ type: 'autogenerated', dirName: 'writing_your_suite' }],
    },
    {
      type: 'category',
      label: 'Writing Tests',
      items: [{ type: 'autogenerated', dirName: 'writing_tests' }],
    },
    {
      type: 'category',
      label: 'Enforce (Assertions)',
      items: [{ type: 'autogenerated', dirName: 'enforce' }],
    },
    {
      type: 'category',
      label: 'Utilities',
      items: [{ type: 'autogenerated', dirName: 'utilities' }],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [{ type: 'autogenerated', dirName: 'recipes' }],
    },
    'understanding_state',
    'suite_serialization',
    'server_side_validations',
    'typescript_support',
    'api_reference',
    {
      type: 'category',
      label: 'Community Resources',
      items: [{ type: 'autogenerated', dirName: 'community_resources' }],
    },
    'vest_vs_the_rest',
    'upgrade_guide',
  ],
};

module.exports = sidebars;
