name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: latest
          fetch-depth: 0
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
      - name: Push To Nightly Branch
        run: |
          echo "Pushing to nightly branch"
          git push origin HEAD:nightly --force
