name: Release

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - release
  pull_request:
    branches:
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Install
      #   run: yarn install --frozen-lockfile
      # - name: Build
      #   run: yarn build
      # - name: Lint
      #   run: yarn lint
      # - name: Test
      #   run: yarn test
      # - name: Set npmrc
      #   run: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
      #   env:
      #     NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Release
        run: node ./scripts/check.js
        # run: node ./scripts/release.js
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RELEASE_BRANCH: release
          STABLE_BRANCH: stable
          LATEST_BRANCH: latest
          CURRENT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
